### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by 3t8**
Updated print function to make it compatible with python 3 standards

### CODE REVIEW

**Comment by tuladhar** [comment]
Thanks @3t8

**Review by tuladhar — APPROVED** [review]

**Comment by 3t8** [comment]
Can you fix the typo on the project topic from 'hactoberfest' to hacktoberfest' please?

**Comment by tuladhar** [comment]
Thanks for reporting @3t8. Fixed it.

**Comment by 3t8** [comment]
Thank you

**Pull request merged**
